s@SDDDdfsdasss
MadhurangaWije/github-connector pull request #103
Opened 2020-12-21 20:54 UTC by MadhurangaWije

ssad

2020-12-21 21:08 UTC, ravindra-wije commented
sdfsd

2020-12-21 21:09 UTC, ravindra-wije reviewed
this is review comment feedbackasffaas

2020-12-21 21:14 UTC, MadhurangaWije reviewed
adsadfsadf

2020-12-21 21:14 UTC, MadhurangaWije reviewed
asas

2020-12-21 21:18 UTC, MadhurangaWije reviewed
asdasd

2020-12-22 01:59 UTC, MadhurangaWije reviewed
asd

2020-12-22 02:03 UTC, MadhurangaWije reviewed
adasf

2020-12-22 02:16 UTC, MadhurangaWije reviewed
sdsdf

2020-12-22 02:22 UTC, MadhurangaWije reviewed
adfasf

1. sdf
2. sdf
3. sdf
4. sdfs
5. df
6. s
7. dfs
8. df

2020-12-22 02:23 UTC, ravindra-wije reviewed
pppppppppppppppppppppp

2020-12-22 02:26 UTC, ravindra-wije requested changes
change this file

2020-12-22 02:28 UTC, ravindra-wije reviewed
sdfsd

2020-12-22 02:29 UTC, MadhurangaWije commented
> sdfsd

what do i mean by this

2020-12-22 02:38 UTC, MadhurangaWije commented
> sdfsd

jis
s
ss
s


s
s
s

s

2020-12-22 02:42 UTC, MadhurangaWije commented
> pppppppppppppppppppppp

sdfkjsd 
sdf
sdf
sd
f
sdf
sdf**sdfsdfsdfsd**

2020-12-22 03:03 UTC, MadhurangaWije commented on src/db/main.bal
asdasd

2020-12-22 03:03 UTC, MadhurangaWije commented on src/db/main.bal
> +    // some changes 22
asdfasf

2020-12-22 03:06 UTC, MadhurangaWije commented
> sdfsd

sdfs
sdf
s
df
s                                                     asddddddddddddddddddddddddddddddd
df
sdm

2020-12-22 03:16 UTC, MadhurangaWije reviewed
pr review comment

2020-12-22 03:16 UTC, MadhurangaWije commented on src/db/main.bal
> +    // some changes 22
this is pull request review comment

2020-12-22 03:22 UTC, MadhurangaWije reviewed
remove commented liens

2020-12-22 03:22 UTC, MadhurangaWije commented on src/db/main.bal
> -    // some changes 2
remove this line

2020-12-22 03:22 UTC, MadhurangaWije commented on src/db/main.bal
> -    // some changes 2
dddd

2020-12-22 04:29 UTC, closed without merging